#!/bin/bash
# Crea una arhivo .gitattributes que lista archivos típicos
# que deben ser incluidos por git como lfs.
# @author molavec
# @website www.molavec.com


#Custom
echo "#Añade aquí archivos que desees añadir" >> .gitattributes &&\

#Imagen
echo "Añade extensiones de imagen..."  &&\
echo "#Extensiones de imagen" >> .gitattributes &&\
echo "*.jpg filter=lfs diff=lfs merge=lfs -text" >> .gitattributes &&\
echo "*.svg filter=lfs diff=lfs merge=lfs -text" >> .gitattributes &&\
echo "*.png filter=lfs diff=lfs merge=lfs -text" >> .gitattributes &&\
echo "*.jpeg filter=lfs diff=lfs merge=lfs -text" >> .gitattributes &&\

#Video
echo "Añade extensiones de video..."  &&\
echo "" >> .gitattributes &&\
echo "#Extensiones de video" >> .gitattributes &&\
echo "*.mp4 filter=lfs diff=lfs merge=lfs -text" >> .gitattributes &&\
echo "*.mov filter=lfs diff=lfs merge=lfs -text" >> .gitattributes &&\

#Archivos de Compresión
echo "Añade extensiones de compresión de archivos..."  &&\
echo "" >> .gitattributes &&\
echo "#Extensiones de video" >> .gitattributes &&\
echo "*.rar filter=lfs diff=lfs merge=lfs -text" >> .gitattributes &&\
echo "*.7z filter=lfs diff=lfs merge=lfs -text" >> .gitattributes &&\
echo "*.zip filter=lfs diff=lfs merge=lfs -text" >> .gitattributes &&\

#Sketch
echo "Añade extensiones de compresión de archivos..."  &&\
echo "" >> .gitattributes &&\
echo "#Extensiones de video" >> .gitattributes &&\
echo "*.sketch filter=lfs diff=lfs merge=lfs -text" >> .gitattributes